#!/usr/bin/env Rscript

# ==============================================================================
# Provenance audit
# Project: mateR2 Manuscript
#
# Confirms that every number and figure the manuscript cites traces to ONE
# coherent execution of the current code. Checks, in order:
#
#   1. Working tree is clean (uncommitted edits mean outputs may not match code)
#   2. Every output postdates the newest source file
#   3. Outputs postdate the installed mateR2 build
#   4. The mateR2 version recorded inside the chain files matches the installed one
#   5. All 90 chain files are present and share one mateR2 version
#   6. Derived outputs postdate the chains they are derived from
#
# Not part of the pipeline. Run before submission:
#     Rscript scripts/audit_provenance.R
# Exits non-zero if anything is stale.
# ==============================================================================

fail <- character()
note <- function(ok, msg) {
  cat(sprintf("  [%s] %s\n", ifelse(ok, "ok", "!!"), msg))
  if (!ok) fail <<- c(fail, msg)
}
hdr <- function(x) cat(sprintf("\n%s\n%s\n", x, strrep("-", nchar(x))))

cat(strrep("=", 78), "\nProvenance audit\n", strrep("=", 78), "\n", sep = "")

# --- 1. Clean tree ------------------------------------------------------------
hdr("1. Repository state")
st <- suppressWarnings(try(system2("git", c("status", "--porcelain"),
                                   stdout = TRUE, stderr = TRUE), silent = TRUE))
if (inherits(st, "try-error")) {
  cat("  [--] git unavailable; skipping\n")
} else {
  dirty <- st[!grepl("^\\?\\?", st)]           # ignore untracked
  note(length(dirty) == 0,
       sprintf("working tree clean (%d tracked file(s) modified)", length(dirty)))
  if (length(dirty)) cat(paste0("       ", dirty, collapse = "\n"), "\n")
  sha <- try(system2("git", c("rev-parse", "--short", "HEAD"), stdout = TRUE), silent = TRUE)
  if (!inherits(sha, "try-error")) cat("       HEAD:", sha, "\n")
}

# --- 2. Outputs vs the script that produces them ------------------------------
# Comparing every output against the NEWEST script is too blunt: editing one
# plotting script would mark every chain file stale even though nothing that
# produces chains changed. Each output is checked against its own producer, and
# against the upstream scripts it genuinely depends on.
hdr("2. Outputs vs the code that produces them")

produced_by <- list(
  # output pattern                     = scripts it depends on (in order)
  "data/outputs/chains/"               = c("01_setup_scenarios.R", "02_run_mcmc_chains.R"),
  "data/outputs/mcmc_convergence"      = c("01_setup_scenarios.R", "02_run_mcmc_chains.R",
                                           "03_convergence_stats.R"),
  "figures/Figure_03"                  = c("03_convergence_stats.R", "04_generate_mateR2_figures.R"),
  "figures/Figure_S01"                 = c("03_convergence_stats.R", "04_generate_mateR2_figures.R"),
  "figures/Figure_04"                  = c("05_topology_validation.R"),
  "figures/topology_grid_summary"      = c("05_topology_validation.R"),
  "figures/Figure_05"                  = c("06_sibling_dynamics.R"),
  "figures/Figure_06"                  = c("06_sibling_dynamics.R"),
  "data/outputs/extended_sib"          = c("06_sibling_dynamics.R"),
  "figures/Figure_01"                  = c("07_figure_1_Bipartite_Network_visuals.R"),
  "figures/Figure_02"                  = c("08_figure_2_worked_Example.R"),
  "data/outputs/sibling_asymmetry"     = c("09_sibling_asymmetry_mechanism.R"),
  "figures/Figure_S02"                 = c("10_weight_sensitivity.R")
)

outs <- c(list.files("data/outputs", full.names = TRUE, recursive = TRUE),
          list.files("figures", full.names = TRUE))
# Step 10 is opt-in and its outputs are cached by design; neither the sweep
# nor the figure built from it is regenerated by the default run.
outs <- outs[!grepl("weight_sensitivity", outs, ignore.case = TRUE) &
               !grepl("Figure_S02", outs)]

if (!length(outs)) {
  note(FALSE, "no outputs found -- run scripts/00_run_all.R")
} else {
  stale <- character(); orphan <- character()
  for (f in outs) {
    hit <- names(produced_by)[vapply(names(produced_by),
                                     function(k) grepl(k, f, fixed = TRUE), logical(1))]
    if (!length(hit)) { orphan <- c(orphan, f); next }
    deps <- file.path("scripts", produced_by[[hit[1]]])
    deps <- deps[file.exists(deps)]
    if (length(deps) && file.mtime(f) < max(file.mtime(deps))) stale <- c(stale, f)
  }
  note(length(stale) == 0,
       sprintf("all %d outputs postdate their own producing script(s) (%d stale)",
               length(outs), length(stale)))
  if (length(stale)) cat(paste0("       ", head(stale, 12), collapse = "\n"), "\n")
  # An output with no producing script cannot be regenerated and should not ship.
  note(length(orphan) == 0,
       sprintf("every output has a producing script (%d orphaned)", length(orphan)))
  if (length(orphan)) cat(paste0("       ", head(orphan, 12), collapse = "\n"), "\n")
}

# --- 3 & 4. Package build and recorded version --------------------------------
hdr("3. mateR2 build")
pkg_v <- as.character(utils::packageVersion("mateR2"))
pkg_t <- file.mtime(system.file("DESCRIPTION", package = "mateR2"))
cat(sprintf("  installed mateR2 %s, built %s\n", pkg_v, format(pkg_t, "%Y-%m-%d %H:%M")))
if (length(outs)) {
  older <- outs[file.mtime(outs) < pkg_t]
  note(length(older) == 0,
       sprintf("all outputs postdate the installed package build (%d predate it)",
               length(older)))
}

hdr("4. Version recorded inside the chain files")
cf <- list.files("data/outputs/chains", "^scenario_.*\\.rds$", full.names = TRUE)
note(length(cf) == 90, sprintf("chain files present: %d (expected 90)", length(cf)))
if (length(cf)) {
  vs <- unique(vapply(cf, function(f) {
    x <- readRDS(f); v <- x$mateR2_version
    if (is.null(v)) NA_character_ else as.character(v)
  }, character(1)))
  note(length(vs) == 1, sprintf("single mateR2 version across chains: %s",
                                paste(vs, collapse = ", ")))
  note(identical(vs[1], pkg_v),
       sprintf("chains built with the installed version (%s vs %s)", vs[1], pkg_v))
}

# --- 5. Derived outputs postdate the chains -----------------------------------
hdr("5. Derivation order")
if (length(cf)) {
  ch_t <- max(file.mtime(cf))
  derived <- c("data/outputs/mcmc_convergence_summary.csv",
               "data/outputs/mcmc_convergence_by_seed.csv",
               "data/outputs/extended_sib_and_parent_stats.rds",
               "data/outputs/sibling_asymmetry_cells.csv",
               "figures/Figure_03_MCMC_Diagnostics.png",
               "figures/Figure_S01_Target_Fidelity_Error.png")
  derived <- derived[file.exists(derived)]
  bad <- derived[file.mtime(derived) < ch_t]
  note(length(bad) == 0,
       sprintf("all %d derived outputs postdate the newest chain file (%d stale)",
               length(derived), length(bad)))
  if (length(bad)) cat(paste0("       ", bad, collapse = "\n"), "\n")
  missing <- setdiff(c("data/outputs/mcmc_convergence_summary.csv",
                       "data/outputs/sibling_asymmetry_cells.csv"), derived)
  if (length(missing)) note(FALSE, paste("missing expected output:", paste(missing, collapse = ", ")))
}

# --- Verdict ------------------------------------------------------------------
cat("\n", strrep("=", 78), "\n", sep = "")
if (!length(fail)) {
  cat("PASS - every output traces to the current code and package build.\n")
} else {
  cat(sprintf("FAIL - %d issue(s):\n", length(fail)))
  cat(paste0("  - ", fail, collapse = "\n"), "\n")
  cat("\nRe-run the full pipeline:  Rscript scripts/00_run_all.R\n")
  cat("(delete data/outputs/chains first to force regeneration)\n")
}
cat(strrep("=", 78), "\n")
# Non-zero exit so this can gate a release step or CI check. Under
# `source()` in RStudio quit() would close the session, so only exit when
# running non-interactively.
if (!interactive()) quit(status = if (length(fail)) 1 else 0, save = "no")